"""users.active changed to no null

Revision ID: 00c2dd4dc5e8
Revises: 955cc9b582a2
Create Date: 2018-06-13 23:35:03.662183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00c2dd4dc5e8'
down_revision = '955cc9b582a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.alter_column('users', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
